export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

//-------------------------------------------------------------
export const CHANGE_DAY = 'CHANGE_DAY';
export type CHANGE_DAY = typeof CHANGE_DAY;

export const UPDATE_WORKSTATIONS = 'UPDATE_WORKSTATIONS';
export type UPDATE_WORKSTATIONS = typeof UPDATE_WORKSTATIONS;

export const UPDATE_FIELD_VALUE = 'UPDATE_FIELD_VALUE';
export type UPDATE_FIELD_VALUE = typeof UPDATE_FIELD_VALUE;

export const CHANGE_NAME = 'CHANGE_NAME';
export type CHANGE_NAME = typeof CHANGE_NAME;